name: mtdna-ml
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - pip
  - samtools
  - r-base
  - numpy
  - pandas
  - scipy
  - regex
  - pyfaidx
  - pysam
  - xgboost
  - scikit-learn
